{"uuid": "2e7dae9e-24e6-413c-bdc5-3c56334cecac", "children": ["ce94ccac-e5c0-404b-984e-63983facfda6"], "befores": [{"name": "drivers", "status": "broken", "statusDetails": {"message": "NameError: name 'driver' is not defined\n", "trace": "  File \"D:\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\TestTools\\python_project\\real_world_web_test\\conftest.py\", line 18, in drivers\n    if driver is None:\n"}, "start": 1635211698599, "stop": 1635211698599}], "start": 1635211698599, "stop": 1635211698649}